version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  
    commands:
      - apt update
      - apt-get -y install \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common \
        python-pip ec2-instance-connect s3fs
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
      - apt-get update
      - apt-get -y install docker-ce=5:19.03.6~3-0~ubuntu-bionic docker-ce-cli=5:19.03.6~3-0~ubuntu-bionic containerd.io
      - usermod -aG docker ubuntu
      - pip install awscli