version: 0.2
phases:
  install:
    commands:
      - echo PREPARANDO O AMBIENTE PARA BUILD...
      - apt-get update
  pre_build:
    commands:
      - echo FAZENDO SOMENTE UM TESTE DE BUILD...
      - docker build -t fastapi-test .